---
id: https://github.com/airr-knowledge/ak-schema
name: ak-schema

classes:

  QueryObject:
    attributes:
      tcr:
        range: QueryTCR
        multivalued: false
        inlined: true
      bcr:
        range: QueryIG
        multivalued: false
        inlined: true
      experiment:
        range: QueryExperiment
        multivalued: false
        inlined: true

  QueryTCR:
    attributes:
      receptor:
        range: TCellReceptor
        multivalued: false
        inlined: true
      mhc:
      epitope:
        range: Epitope
        multivalued: false
        inlined: true
      antigen:

  QueryAlphaBetaTCR:
    is_a: TCellReceptor
    attributes:
      tra_chain:
        range: Chain
        multivalued: false
        inlined: true
      trb_chain:
        range: Chain
        multivalued: false
        inlined: true

  QueryIG:
    attributes:
      receptor:
        range: BCellReceptor
        multivalued: false
        inlined: true
      antigen:

  QueryExperiment:
    slots:
      - akc_id
    attributes:
      assay:
        range: Assay
        multivalued: false
        inlined: true
      specimen:
        range: Specimen
        multivalued: false
        inlined: true
      participant:
        range: Participant
        multivalued: false
        inlined: true
      investigation:
        range: Investigation
        multivalued: false
        inlined: true

#  QueryInvestigation:
#    slots:
#      - investigation_type
#      - archival_id
#      - inclusion_exclusion_criteria
#      - release_date
#      - update_date
#      - documents
#      - conclusions

#  QueryParticipant:
#    slots:
#      - study_arm
#      - species
#      - sex
#      - age
#      - age_unit
#      - age_event
#      - race
#      - ethnicity
#      - geolocation
#      - strain
#      - life_events
